### ISSUE TITLE
Convert any portion of the App to Kotlin

### ISSUE THREAD

**Issue by mayorJAY** [mayorJAY/FlowOverStack#9]
In a bid to migrate the App to 100% Kotlin, contribute by converting a single class or fragment to Kotlin (the least should be converting a whole .java file to .kt - this means that you should do more than converting just a method or a portion of a file). This is a work in progress and will definitely give birth to several Pull Requests.

**Comment by AlecsisDuarte** [comment]
Hi @mayorJAY,
I'll be glad to migrate `AnswerFragment`, `QuestionsByActivityFragment` & `SearchFragment` classes to Kotlin, if that's okay!

**Comment by mayorJAY** [comment]
Sure, go ahead @AlecsisDuarte

**Comment by AlecsisDuarte** [comment]
#28 created the PR
Let me know if you would like me to make any changes!!

**Comment by mayorJAY** [comment]
@AlecsisDuarte I dropped a couple of coments

**Comment by AlecsisDuarte** [comment]
@mayorJAY Addressed the comments and pushed another commit, let me know if you have any other request!
